#!/bin/bash
#SBATCH --job-name=finalize_agg
#SBATCH --time=00:30:00
#SBATCH --mem=16G
#SBATCH --cpus-per-task=1
#SBATCH --output=logs/finalize_%j.out
#SBATCH --error=logs/finalize_%j.err

# =============================================================================
# FINALIZE AGGREGATION SCRIPT
# =============================================================================
# This script combines all partial summaries generated by parallel SLURM jobs
# and generates the final QA HTML report.
#
# Usage:
#   Option 1 - Submit as dependency after array job:
#       JOB_ID=$(sbatch --parsable run_aggregate_slurm.sh)
#       sbatch --dependency=afterok:$JOB_ID finalize_aggregation.sh
#
#   Option 2 - Run directly after all jobs complete:
#       bash finalize_aggregation.sh
#
#   Option 3 - Submit standalone:
#       sbatch finalize_aggregation.sh
# =============================================================================

set -e

# Directory containing this script
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AGG_CONFIG="${SCRIPT_DIR}/config.yaml"

echo "=================================================="
echo "FINALIZE AGGREGATION"
echo "=================================================="
echo "Script directory: $SCRIPT_DIR"
echo "Config: $AGG_CONFIG"
echo "Start time: $(date)"
echo "=================================================="

# Activate conda environment
source ~/.bashrc
conda activate eeg

# Run finalization
python "$SCRIPT_DIR/aggregate_markers_by_probe.py" --config "$AGG_CONFIG" --finalize

echo ""
echo "=================================================="
echo "FINALIZATION COMPLETE"
echo "End time: $(date)"
echo "=================================================="
